spring:
  datasource:
    username: root
    password: 1008611		#mysql对编码格式的要求以及时区确定
    url: jdbc:mysql://172.17.0.2:3306/blog?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://47.114.51.237:3306/blog?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml   #Scan mybatis.xml file
  mapper-locations: classpath:mybatis/mapper/*.xml    #Scan mapper.xml file

